{
 "title": "metrics-app-demo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current Queue Size",
   "type": "gauge",
   "description": "This shows the current number of items in the queue as a speedometer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "custom_queue_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg Process Duration",
   "type": "timeseries",
   "description": "This shows the average time (in seconds) your API takes to respond",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(custom_process_duration_seconds_sum[1m]) / rate(custom_process_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "This shows how many requests are coming in per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(custom_request_count_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}